import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import 'slick-carousel/slick/slick.css'
import 'slick-carousel/slick/slick-theme.css'




export const metadata: Metadata = {
  title: "Scriptly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Navbar />
        <main className="">
        {children}
        </main>
        <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
