import type { Metadata } from "next";
// import "../globals.css";
import '../../globals.css';
import TopBar from "./TopBar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Dashboard/AppSidebar";
import { chown } from "fs";
export const metadata: Metadata = {
  title: "Scriptly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
  <SidebarProvider>
      <main className="antialiased flex w-screen">
        <AppSidebar/>
        <div className="flex flex-col gap-10  min-h-screen w-full">

               <TopBar/>
        <div className="">{children}</div>
        </div>
     
       
      </main>
     </SidebarProvider>
 
  );
}

