import type { Metadata } from "next";
// import "../globals.css";
import '../../globals.css';
import TopBar from "./TopBar";

export const metadata: Metadata = {
  title: "Scriptly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" 
     className="light"
    
    >
      <body className="antialiased">
        <TopBar/>
       
      </body>
    </html>
  );
}

